//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IOperationService")]
public interface IOperationService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperationService/Start", ReplyAction="http://tempuri.org/IOperationService/StartResponse")]
    void Start(string userName);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperationService/Start", ReplyAction="http://tempuri.org/IOperationService/StartResponse")]
    System.Threading.Tasks.Task StartAsync(string userName);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperationService/Stop", ReplyAction="http://tempuri.org/IOperationService/StopResponse")]
    void Stop(string userName);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperationService/Stop", ReplyAction="http://tempuri.org/IOperationService/StopResponse")]
    System.Threading.Tasks.Task StopAsync(string userName);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IOperationServiceChannel : IOperationService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class OperationServiceClient : System.ServiceModel.ClientBase<IOperationService>, IOperationService
{
    
    public OperationServiceClient()
    {
    }
    
    public OperationServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public OperationServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public OperationServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public OperationServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public void Start(string userName)
    {
        base.Channel.Start(userName);
    }
    
    public System.Threading.Tasks.Task StartAsync(string userName)
    {
        return base.Channel.StartAsync(userName);
    }
    
    public void Stop(string userName)
    {
        base.Channel.Stop(userName);
    }
    
    public System.Threading.Tasks.Task StopAsync(string userName)
    {
        return base.Channel.StopAsync(userName);
    }
}
